{
  lib,
  stdenv,
  fetchFromGitHub,
  autoPatchelfHook,
  buildGoModule,
  buildNpmPackage,
  nodejs_22,
  electron,
  makeWrapper,
  copyDesktopItems,
  makeDesktopItem,
  nix-update-script,
}:

let
  pname = "outlinevpn-client";
  version = "1.21.2-rc.1";

  src = fetchFromGitHub {
    owner = "OutlineFoundation";
    repo = "outline-apps";
    tag = "client_linux/v${version}";
    hash = "sha256-U6CUnDClScNT5jMJ2TsYI1fUjQWOLScMyEr4LtVc5mU=";
  };

  # The Electron main process looks the Go artifacts up in
  # `output/client/linux-<GOARCH>/` (see client/electron/app_paths.ts).
  goArch = stdenv.hostPlatform.go.GOARCH;
  electronArch = if stdenv.hostPlatform.isx86_64 then "x64" else "arm64";

  # Go backend: the `tun2socks` helper binary and `libbackend.so`, a c-shared
  # library that the Electron main process loads through koffi to set up the
  # TUN device, routing and the tunnel.
  backend = buildGoModule {
    pname = "${pname}-backend";
    inherit version src;

    vendorHash = "sha256-cv2LSica0s5Vm83u0CSY/sAK06bjf/cgOpZDv6WoUuI=";
    # go-tun2socks ships lwIP C sources in directories without Go files,
    # which `go mod vendor` drops.
    proxyVendor = true;

    subPackages = [ "client/go/outline/electron" ];

    ldflags = [
      "-s"
      "-w"
      "-X main.version=${version}"
    ];

    postBuild = ''
      go build -trimpath -buildmode=c-shared -ldflags="$ldflags" \
        -o libbackend.so ./client/go/outline/electron
    '';

    postInstall = ''
      mv $out/bin/electron $out/bin/tun2socks
      install -Dm644 libbackend.so $out/lib/libbackend.so
    '';
  };
in
buildNpmPackage (finalAttrs: {
  inherit pname version src;

  nodejs = nodejs_22;
  npmDepsHash = "sha256-8nj0yKneNykulM1x1W97LFJkDlU49mHyfdwiMQ8hclU=";
  # ShadowsocksConfig is a git dependency with a `build` script but no
  # lockfile; its build output is committed, so nothing needs to run.
  forceGitDeps = true;
  # npm needs to write to the cache to unpack the git dependencies.
  makeCacheWritable = true;

  patches = [
    # Upstream's lockfile is not usable offline: ~830 entries lack
    # `resolved`/`integrity` (npm/cli#4263), and a few nested entries under
    # the client/capacitor workspace are stale, so `npm ci` goes to the
    # registry to re-resolve them. Generated by running
    # `npm-lockfile-fix -r package-lock.json` and then dropping the stale
    # entries (client/capacitor/node_modules/webpack-{cli,dev-server,merge}
    # and src/cordova/plugin), which `npm ci` prunes anyway.
    #
    # It also bumps koffi 2.12.0 -> 2.16.3 (within upstream's ^2.12.0 range):
    # 2.12.0 deadlocks on exit with the Node bundled in current Electron
    # (fixed in koffi 2.15.2), which left the app hanging after quitting.
    ./package-lock.patch
  ];

  nativeBuildInputs = [
    autoPatchelfHook
    copyDesktopItems
    makeWrapper
  ];

  # koffi's prebuilt native module links against libstdc++.
  buildInputs = [ (lib.getLib stdenv.cc.cc) ];

  # Nothing needs to be compiled or downloaded: koffi ships prebuilt binaries,
  # and the install scripts of electron, puppeteer and sharp only download
  # things we don't use.
  npmRebuildFlags = [ "--ignore-scripts" ];

  postPatch = ''
    # Release builds insist on a Sentry DSN; we don't ship crash reporting.
    substituteInPlace client/web/build.action.mjs \
      --replace-fail "if (buildMode === 'release') {" "if (buildMode === 'release' && sentryDsn) {"

    # The preload script uses Node modules (node:os), which the renderer
    # sandbox that is on by default since Electron 20 does not allow.
    # Upstream still builds with Electron 19.
    substituteInPlace client/electron/index.ts \
      --replace-fail "contextIsolation: true," "contextIsolation: true, sandbox: false,"
  '';

  # Builds the web UI (client/www) and the Electron main + preload bundles
  # (output/client/electron). The Go backend is built separately above and
  # electron-builder is not used at all.
  buildPhase = ''
    runHook preBuild

    node infrastructure/build/run_action.mjs client/electron/build_main linux \
      --arch=${electronArch} \
      --buildMode=release \
      --versionName=${version}

    runHook postBuild
  '';

  installPhase = ''
    runHook preInstall

    appDir=$out/share/${pname}
    binDir=$appDir/output/client/linux-${goArch}
    mkdir -p $appDir/client/electron/icons $appDir/output/client $binDir

    cp -r client/www $appDir/client/
    mkdir -p $appDir/client/resources
    cp -r client/resources/tray $appDir/client/resources/
    cp -r client/electron/icons/png $appDir/client/electron/icons/
    cp -r output/client/electron $appDir/output/client/

    # webpack's node-loader emitted koffi's prebuilt native module for every
    # platform koffi supports; keep only the one for this platform.
    for f in $appDir/output/client/electron/*.node; do
      cmp -s "$f" node_modules/koffi/build/koffi/linux_${electronArch}/koffi.node || rm "$f"
    done

    ln -s ${backend}/bin/tun2socks $binDir/tun2socks
    ln -s ${backend}/lib/libbackend.so $binDir/libbackend.so

    # Mirrors what electron-builder generates from electron-builder.json's
    # `extraMetadata`.
    cat > $appDir/package.json <<EOF
    {
      "name": "outline-client",
      "productName": "Outline",
      "version": "${version}",
      "main": "output/client/electron/index.js"
    }
    EOF

    for size in 16 24 32 48 64 128 256 512 1024; do
      install -Dm644 client/electron/icons/png/''${size}x''${size}.png \
        $out/share/icons/hicolor/''${size}x''${size}/apps/${pname}.png
    done

    makeWrapper ${lib.getExe electron} $out/bin/${pname} \
      --add-flags $appDir \
      --add-flags "\''${NIXOS_OZONE_WL:+\''${WAYLAND_DISPLAY:+--ozone-platform-hint=auto --enable-features=WaylandWindowDecorations --enable-wayland-ime=true}}" \
      --inherit-argv0

    runHook postInstall
  '';

  desktopItems = [
    (makeDesktopItem {
      name = pname;
      desktopName = "Outline";
      genericName = "VPN Client";
      comment = "Access the open internet with Outline VPN";
      exec = "${pname} %U";
      icon = pname;
      categories = [ "Network" ];
      mimeTypes = [
        "x-scheme-handler/ss"
        "x-scheme-handler/ssconf"
      ];
      startupWMClass = "Outline";
      terminal = false;
    })
  ];

  passthru = {
    inherit backend;
    updateScript = nix-update-script {
      extraArgs = [ "--version-regex=^client_linux/v(.+)$" ];
    };
  };

  meta = {
    description = "Client for Outline VPN servers";
    longDescription = ''
      Outline is a VPN client for Outline servers, based on Shadowsocks.

      The Linux client establishes the VPN from within the Electron process
      through NetworkManager, so it needs the CAP_NET_ADMIN and
      CAP_DAC_OVERRIDE capabilities. On NixOS, enable
      `programs.outlinevpn-client`, which sets up a capability wrapper.
      Elsewhere, launch it with ambient capabilities, e.g. with capsh:

          sudo capsh --caps="cap_net_admin,cap_dac_override+eip cap_setpcap,cap_setuid,cap_setgid+ep" \
            --keep=1 --user="$USER" --addamb=cap_net_admin,cap_dac_override -- -c outlinevpn-client
    '';
    homepage = "https://getoutline.org/";
    changelog = "https://github.com/OutlineFoundation/outline-apps/releases/tag/client_linux%2Fv${version}";
    license = lib.licenses.asl20;
    mainProgram = pname;
    maintainers = with lib.maintainers; [ angelodlfrtr ];
    platforms = [
      "x86_64-linux"
      "aarch64-linux"
    ];
  };
})
