{
  lib,
  fetchFromGitHub,
  buildNpmPackage,
  nodejs_22,
  electron,
  makeWrapper,
  copyDesktopItems,
  makeDesktopItem,
  nix-update-script,
}:

buildNpmPackage (finalAttrs: {
  pname = "outlinevpn-manager";
  version = "1.21.0-rc.1";

  src = fetchFromGitHub {
    owner = "OutlineFoundation";
    repo = "outline-apps";
    tag = "manager_linux/v${finalAttrs.version}";
    hash = "sha256-wy4tb1M8vZ5AiUMh/2YY1Zq2pK8lSQ+FZMTtjrJc8xk=";
  };

  nodejs = nodejs_22;
  npmDepsHash = "sha256-VyqeiRzTbU5T2pFCpYWqz/p3kaxLhrmRjh8uSlkWUw0=";
  # ShadowsocksConfig is a git dependency with a `build` script but no
  # lockfile; its build output is committed, so nothing needs to run.
  forceGitDeps = true;
  # npm needs to write to the cache to unpack the git dependencies.
  makeCacheWritable = true;

  patches = [
    # Upstream's lockfile is not usable offline: ~840 entries lack
    # `resolved`/`integrity` (npm/cli#4263), and a few nested entries under
    # the client/capacitor workspace are stale, so `npm ci` goes to the
    # registry to re-resolve them. Generated by running
    # `npm-lockfile-fix -r package-lock.json` and then dropping the stale
    # entries (client/capacitor/node_modules/webpack-{cli,dev-server,merge}
    # and src/cordova/plugin), which `npm ci` prunes anyway.
    ./package-lock.patch
  ];

  # Nothing needs to be compiled: the install scripts of electron, puppeteer
  # and sharp only download things this build does not use.
  npmRebuildFlags = [ "--ignore-scripts" ];

  postPatch = ''
    # The updater looks for the app-update.yml that electron-builder would
    # have written, and rejects without it. Updates come from the package
    # manager here, so drop the check entirely.
    substituteInPlace server_manager/electron/index.ts \
      --replace-fail "autoUpdater.checkForUpdates();" "/* updates are handled by the package manager */"
  '';

  nativeBuildInputs = [
    copyDesktopItems
    makeWrapper
  ];

  # Builds the web UI and the Electron main and preload bundles, and
  # assembles them into output/build/server_manager/electron/static. The
  # upstream build then runs electron-builder over that directory to produce
  # an AppImage, which we replace with a wrapper around nixpkgs' electron.
  buildPhase = ''
    runHook preBuild

    # The build actions are shell scripts that invoke `webpack` directly,
    # which npm would normally put on PATH.
    export PATH="$PWD/node_modules/.bin:$PATH"

    node infrastructure/build/run_action.mjs server_manager/electron/build \
      --buildMode=release \
      --versionName=${finalAttrs.version}

    runHook postBuild
  '';

  installPhase = ''
    runHook preInstall

    appDir=$out/share/${finalAttrs.pname}
    mkdir -p $appDir
    cp -r output/build/server_manager/electron/static/. $appDir/

    # The main and preload bundles keep their dependencies external
    # (webpack-node-externals), so they are require()d at runtime. Ship the
    # production closure of the server_manager workspace; the full workspace
    # tree that npm installs is an order of magnitude larger.
    npm ls --omit=dev --all --parseable -w server_manager > npm-ls.txt || true
    grep /node_modules/ npm-ls.txt | sort -u | while read -r dep; do
      rel="node_modules/''${dep#*/node_modules/}"
      # the workspace's link to itself; nothing requires it at runtime
      if [ "$rel" = "node_modules/@outline/server_manager" ]; then
        continue
      fi
      mkdir -p "$appDir/$(dirname "$rel")"
      cp -rL "$dep" "$appDir/$rel"
    done

    for size in 16 24 32 48 64 128 256 512 1024; do
      install -Dm644 server_manager/electron/icons/png/''${size}x''${size}.png \
        $out/share/icons/hicolor/''${size}x''${size}/apps/${finalAttrs.pname}.png
    done

    makeWrapper ${lib.getExe electron} $out/bin/${finalAttrs.pname} \
      --add-flags $appDir \
      --add-flags "\''${NIXOS_OZONE_WL:+\''${WAYLAND_DISPLAY:+--ozone-platform-hint=auto --enable-features=WaylandWindowDecorations --enable-wayland-ime=true}}" \
      --inherit-argv0

    runHook postInstall
  '';

  desktopItems = [
    (makeDesktopItem {
      name = finalAttrs.pname;
      desktopName = "Outline Manager";
      genericName = "VPN Server Manager";
      comment = "Create and manage access to Outline VPN servers";
      exec = finalAttrs.pname;
      icon = finalAttrs.pname;
      categories = [ "Network" ];
      startupWMClass = "Outline Manager";
      terminal = false;
    })
  ];

  passthru.updateScript = nix-update-script {
    extraArgs = [ "--version-regex=^manager_linux/v(.+)$" ];
  };

  meta = {
    description = "Create and manage access to Outline VPN servers";
    longDescription = ''
      Outline Manager is the desktop application for creating Outline VPN
      servers on a cloud provider and handing out access keys for them. The
      servers it creates are used with the Outline client, packaged as
      `outlinevpn-client`.
    '';
    homepage = "https://getoutline.org/";
    changelog = "https://github.com/OutlineFoundation/outline-apps/releases/tag/manager_linux%2Fv${finalAttrs.version}";
    license = lib.licenses.asl20;
    mainProgram = finalAttrs.pname;
    maintainers = with lib.maintainers; [ angelodlfrtr ];
    platforms = [
      "x86_64-linux"
      "aarch64-linux"
    ];
  };
})
